# Generated by Django 4.2.5 on 2023-12-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=30)),
                ('trade_code', models.CharField(max_length=30)),
                ('high', models.CharField(max_length=30)),
                ('low', models.CharField(max_length=30)),
                ('open', models.CharField(max_length=30)),
                ('close', models.CharField(max_length=30)),
                ('volume', models.CharField(max_length=30)),
            ],
        ),
    ]
